name: Playwright Tests  # Назва робочого процесу

on:
  push:  # Тригери на події push
    branches: [ main, master ]  # Тестування на гілках main і master
  pull_request:  # Тригери на події pull request
    branches: [ main, master ]  # Тестування на гілках main і master

jobs:
  test:  # Оголошення роботи з назвою "test"
    timeout-minutes: 60  # Максимальний час виконання роботи в хвилинах
    runs-on: ubuntu-latest  # Виконання роботи буде виконуватися на віртуальній машині на останній версії Ubuntu
    steps:
      - uses: actions/checkout@v4  # Завантаження/клонування коду з поточного репозиторію.
      - name: Set up Python  # Налаштування середовища Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Використання Python версії 3.12
          
      - name: Install dependencies  # Встановлення необхідних залежностей
      # Оновлює pip до останньої версії
      # Встановлення залежностей з файлу requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # На цьому кроці відбувається встановлення браузерів, необхідних для виконання тестів із Playwright, а також необхідних залежностей
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps  # Встановлення браузерів з необхідними залежностями
        
      - name: Run your tests  # Запуск тестів
        # run: pytest -s -v  # Виконання тестів з Pytest в детальному режимі
        run: pytest -s -v --alluredir=reports
        # ЗВЕРНІТЬ УВАГУ: якщо у файлі pytest.ini не вказана директорія для збереження звіту Allure або у вас немає файлу конфігуарції pytest.ini, додайте до команди запуску тестів прапор --alluredir=reports.

      # Цей крок використовує дію actions/upload-artifact@v4 для завантаження артефактів (у разі звіту Allure) з директорії reports/
      - uses: actions/upload-artifact@v4  # Завантаження артефактів
        if: ${{ !cancelled() }}  # Завантаження, якщо робота не скасована
        with:
          name: allure_report  # Назва артефакту
          path: reports/  # Шлях до директорії з артефактами
